spring.application.name=order

server.port=18084

spring.cloud.discovery.enabled=true

logging.level.com.logistic.client.order.application.service=debug

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
management.tracing.sampling.probability=1.0

spring.datasource.url=jdbc:postgresql://localhost:5432/db_order
spring.datasource.username=postgres
spring.datasource.password=5432
spring.jpa.hibernate.ddl-auto=create

